### ISSUE TITLE
Entity Framework Core and .Net Core  support

### ISSUE THREAD

**Issue by gchadid** [NasirJafarzadeh/DynamicQuery.Net#3]
It is planned to support .Net Core and Entity Framework Core?

i try to use it on a .net core 2.0 and EF core but i don't want the dependency of .Net Framework 4.*

also i get this error 

Unable to cast object of type 'Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1[SutaxCapital.WebApiCore.Models.Domain.Poliza]' to type 'System.Linq.IOrderedQueryable`1[SutaxCapital.WebApiCore.Models.Domain.Poliza]'.'

   at DynamicQuery.Net.Extensions.Order[T](IQueryable`1 input, List`1 orderInput)
   at DynamicQuery.Net.Extensions.Filter[T](IQueryable`1 input, DynamicQueryNetInput dynamicInput)
   at SutaxCapital.WebApiCore.Api.PolizasController.Get(FilterViewModel filtros) in C:\Users\gchadid\Desktop\sucapital\backend\SutaxCapital.WebApiCore\Api\PolizasController.cs:line 42
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()

**Comment by nasirjd** [comment]
Hi my friend, thanks for your Issue, I will make it available for dotnet core 2.0

**Comment by wlclass** [comment]
@NasirJafarzadeh  thanks for your work . I intend to use it on .Net Core 2.0.
please fix this nuget package

**Comment by nasirjd** [comment]
Hi buddies!
Finally! the package is available for dotnet core 2.0
Hope it will be helpful
